version: "3.9"
services:
  php-app:
    container_name: php_app
    ports:
      - "8081:80"
    build: './build/php'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    container_name: db
    ports:
      - "3307:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "shroot"
      MYSQL_DATABASE: "my_harmony"
    volumes:
      - dbData:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8082:80'

volumes:
  src:
  dbData: